/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include "sysmem.h"
#include <errno.h>
#include <stdint.h>

/* Stack paint value used to detect peak stack usage */
#define STACK_PAINT_VALUE 0xDEADBEEFU

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;
static uint8_t *__sbrk_heap_peak = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr) {
  extern uint8_t _end;             /* Symbol defined in the linker script */
  extern uint32_t _estack;         /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end) {
    __sbrk_heap_end = &_end;
    __sbrk_heap_peak = &_end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap) {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  if (__sbrk_heap_end > __sbrk_heap_peak) {
    __sbrk_heap_peak = __sbrk_heap_end;
  }

  return (void *)prev_heap_end;
}

float Heap_GetPeakUsage(void) {
  extern uint8_t _end;
  extern uint32_t _Min_Heap_Size; /* Symbol defined in the linker script */
  if (__sbrk_heap_peak == NULL)
    return 0.0f;
  return (float)(__sbrk_heap_peak - &_end) / (float)_Min_Heap_Size;
}

uint32_t Heap_GetCurrentUsage(void) {
  extern uint8_t _end;
  if (__sbrk_heap_end == NULL)
    return 0;
  return (uint32_t)(__sbrk_heap_end - &_end);
}

void Stack_Paint(void) __attribute__((naked, section(".text.startup")));
void Stack_Paint(void) {
  __asm volatile("ldr r0, =_sstack          \n"
                 "ldr r1, =0xDEADBEEF       \n"
                 "mov r2, sp                \n"
                 "paint_loop:               \n"
                 "cmp r0, r2                \n"
                 "bge paint_done            \n"
                 "str r1, [r0], #4          \n"
                 "b   paint_loop            \n"
                 "paint_done:               \n"
                 "bx  lr                    \n");
}

float Stack_GetPeakUsage(void) {
  // NOLINTNEXTLINE
  extern uint32_t _sstack;
  // NOLINTNEXTLINE
  extern uint32_t _estack;

  uint32_t *p = &_sstack;

  while (*p == STACK_PAINT_VALUE && p < &_estack) {
    p++;
  }

  uint32_t total = (uint32_t)(&_estack - &_sstack) * sizeof(uint32_t);
  uint32_t peak = (uint32_t)(&_estack - p) * sizeof(uint32_t);

  return ((float)peak) / ((float)total);
}
